### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GoldenSpringFox** [GoldenSpringFox/Intro2cs_Ex11#1]
General:
- [x] fill this todo list
- [x] signup for an interview

Gui:
- [x] create skeleton
- [x] timer
- [x] submit
- [x] clear
- [x] welcome page
- [x] try again
- [x] list of completed words

Model:
- [x] utility functions
- [x] initialize board
- [x] add/remove cell to route
- [x] check word validity
- [x] score

Controller:
- [x] hook up model and gui

QL Features:
- [x] color path when correct
- [ ] mark path direction
